In [1]:
import numpy as np

# np.random.rand(d1, d2, ... , dn)
- 产生维度为(d1, d2, ... , dn)，值在[0,1）的正态分布

In [3]:
print("x1 = np.random.rand(1)\n", np.random.rand(1))
print("x2 = np.random.rand(1, 3)\n", np.random.rand(1, 3))
print("x3 = np.random.rand(3, 1)\n", np.random.rand(3, 1))
print("x4 = np.random.rand(3, 5)\n", np.random.rand(3, 5))
print("x5 = np.random.rand(2, 3, 4)\n", np.random.rand(2, 3, 4))

x1 = np.random.rand(1)
 [0.66484886]
x2 = np.random.rand(1, 3)
 [[0.4758461  0.87067598 0.07988648]]
x3 = np.random.rand(3, 1)
 [[0.03060071]
 [0.15117295]
 [0.04484138]]
x4 = np.random.rand(3, 5)
 [[0.56189188 0.83843529 0.75176326 0.55068071 0.82107146]
 [0.18779436 0.96163949 0.3089376  0.6116502  0.82684179]
 [0.69668349 0.48459271 0.28718529 0.43916051 0.00740456]]
x5 = np.random.rand(2, 3, 4)
 [[[0.12944147 0.45150804 0.99931154 0.85093057]
  [0.67987966 0.08924955 0.18876302 0.29043345]
  [0.14890718 0.16496268 0.06130311 0.67538181]]

 [[0.889428   0.1721125  0.86099832 0.52391014]
  [0.08021738 0.17460279 0.64394697 0.30319693]
  [0.56137484 0.01064233 0.94028623 0.28205924]]]


# np.random.randn(d1, d2, ... , dn)
- 生成维度为（d1, d2, ... , dn）的标准正态分布，即（0，1）正太分布，0为均值，1为标准差

In [4]:
print("randn用法 x1 = np.random.randn(3, 5)\n", np.random.randn(3, 5))
print("作为对照  x2 = np.random.rand(3, 5)\n", np.random.rand(3, 5))

randn用法 x1 = np.random.randn(3, 5)
 [[-1.98175067 -1.01850981  1.00577323  2.08569836  0.41075057]
 [ 1.04202622  0.45748661 -0.1179211  -0.34679644  0.95651891]
 [ 1.65527381  0.07137903 -1.35222803  2.12413691  1.07551789]]
作为对照  x2 = np.random.rand(3, 5)
 [[0.87545952 0.59980148 0.80050235 0.18334831 0.24830396]
 [0.3911433  0.53282022 0.65225236 0.51462994 0.04586848]
 [0.69478056 0.36355203 0.40189252 0.05202698 0.84241243]]


# np.random.random(size)
- size是生成列表的维度，产生[0,1)的均匀分布

In [5]:
np.random.seed(3)
print("无参数时：np.random.random()\n", np.random.random())
print("参数为数字：np.random.random(3)\n", np.random.random(3))
print("参数为元组：np.random.random((2,3))\n", np.random.random((2,3)))
print("参数为元组：np.random.random((2,3))\n", np.random.random((2,3)))
print("参数为元组：np.random.random((2,3,4))\n", np.random.random((2,3,4)))
print("参数为列表：np.random.random([2,3,4])\n", np.random.random([2,3,4]))

无参数时：np.random.random()
 0.5507979025745755
参数为数字：np.random.random(3)
 [0.70814782 0.29090474 0.51082761]
参数为元组：np.random.random((2,3))
 [[0.89294695 0.89629309 0.12558531]
 [0.20724288 0.0514672  0.44080984]]
参数为元组：np.random.random((2,3))
 [[0.02987621 0.45683322 0.64914405]
 [0.27848728 0.6762549  0.59086282]]
参数为元组：np.random.random((2,3,4))
 [[[0.02398188 0.55885409 0.25925245 0.4151012 ]
  [0.28352508 0.69313792 0.44045372 0.15686774]
  [0.54464902 0.78031476 0.30636353 0.22195788]]

 [[0.38797126 0.93638365 0.97599542 0.67238368]
  [0.90283411 0.84575087 0.37799404 0.09221701]
  [0.6534109  0.55784076 0.36156476 0.2250545 ]]]
参数为列表：np.random.random([2,3,4])
 [[[0.40651992 0.46894025 0.26923558 0.29179277]
  [0.4576864  0.86053391 0.5862529  0.28348786]
  [0.27797751 0.45462208 0.20541034 0.20137871]]

 [[0.51403506 0.08722937 0.48358553 0.36217621]
  [0.70768662 0.74674622 0.69109292 0.68918041]
  [0.37360012 0.6681348  0.33984866 0.57279387]]]


# np.random.choice(a, size, replace=True, p=None)
- 从数组a(必须是一维的)中选出size个元素，replace为Ture表示可以重复选择，False表示不可以重复选择，p为元素被选中的概率

In [6]:
a = np.arange(10)

n1 = np.random.choice(a, 2)
n2 = np.random.choice(a, 3, replace = False)
n3 = np.random.choice(a, (2,3))  # size参数可以是元组，以表示选出的元素的数组结构

print("数组a：\n", a)
print("从数组a中选出2个元素(可重复)，构成n1:\n", n1)
print("从数组a中选出3个元素（不可重复），构成n2:\n", n2)
print("从数组a中选出(2,3)个元素(可重复)，构成n3:\n", n3)

print("##########   抽签程序   ##########")
names = ['A', 'B', 'C', 'D', 'E']  # 数组a可以是列表
luckydog = np.random.choice(names, 1, p=[0.1, 0.6, 0.1, 0.1, 0.1])  # 分别设置了每个人抽中的概率，注意加和必须是1
print("{}这几个人中，抽中的人是{}".format(str(names), str(luckydog)))

数组a：
 [0 1 2 3 4 5 6 7 8 9]
从数组a中选出2个元素(可重复)，构成n1:
 [0 0]
从数组a中选出3个元素（不可重复），构成n2:
 [8 6 2]
从数组a中选出(2,3)个元素(可重复)，构成n3:
 [[0 4 3]
 [0 8 2]]
##########   抽签程序   ##########
['A', 'B', 'C', 'D', 'E']这几个人中，抽中的人是['A']


# np.random.randint(low, high=None, size=None, dtype='l')
- 在[low,high)随机选出大小为size的整数元素;若不写high，则范围是[0,low)

In [7]:
print("x1 = np.random.randint(3, 9):\n在[3,9)之间随机选一个整数\n", np.random.randint(3, 9))  
print("\nx2 = np.random.randint(3):\n在[0,3)之间随机选一个整数\n", np.random.randint(3))
print("\nx3 = np.random.randint(3.234234):\n在[0,3)之间随机选一个整数,小数部分自动忽略\n", np.random.randint(3.234234))
print("\nx4 = np.random.randint(1, 10, size=(2, 2)):\n在[1,10)之间选4个元素构成（2，2）的数组\n", np.random.randint(1, 10, size=(2, 2)))
print("\nx5 = np.random.randint(7.0, dtype='int64'):\n制定数据类型\n", np.random.randint(7.3452345, dtype='int64'))

x1 = np.random.randint(3, 9):
在[3,9)之间随机选一个整数
 4

x2 = np.random.randint(3):
在[0,3)之间随机选一个整数
 1

x3 = np.random.randint(3.234234):
在[0,3)之间随机选一个整数,小数部分自动忽略
 2

x4 = np.random.randint(1, 10, size=(2, 2)):
在[1,10)之间选4个元素构成（2，2）的数组
 [[5 2]
 [3 3]]

x5 = np.random.randint(7.0, dtype='int64'):
制定数据类型
 3


# np.random.RandomState(<int>)
* 生成一个特定的随机状态（随机种子）
* 括号里一个数字表示一个状态
* 括号里不加数字，每次都是不同的随机状态

In [8]:
rng = np.random.RandomState()
rng.rand(3)

array([0.14182045, 0.38572024, 0.12310382])

In [6]:
for i in range(int(1e8)):
    i+=1