**Tutorial for PyTorch**

@ Create Time: 2024-11-06<br>
@ Follow: https://pytorch.org/tutorials/beginner/basics/intro.html

In [1]:
import torch
import numpy as np

---
# [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)
- Tensors于numpy array非常类似, 只是tensors可以在GPU上进行加速
- tensor和array可以在内存上共享地址, 因此不用copy

## 创建一个Tensor

In [14]:
"""
从列表中创建
"""
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [16]:
"""
从numpy数组中创建
"""
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [17]:
"""
从另一个tensor中创建
"""
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8750, 0.3063],
        [0.5798, 0.7075]]) 



In [18]:
"""
指定形状创建tensor
"""
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5042, 0.1261, 0.6711],
        [0.3839, 0.9466, 0.6415]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 查看tensor的属性

In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
