_2021.03.15_  
_更新日期：2021.11.14_  
**Follow Python数据科学手册 第二章 NumPy入门**

In [1]:
import numpy as np

In [2]:
# 检查NumPy版本
np.__version__

'1.21.2'

# 创建NumPy数组

## np.array
>将已有list转换成NumPy数组

In [3]:
ls = [1, 2, 3, 4, 5]
nls_1 = np.array(ls)
print(nls_1, type(nls_1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
# 使用dtype关键字，指定数组的数据类型，**NumPy要求数组的数据类型必须统一
np.array([1, 2, 6, 3], dtype='float32') # NumPy标准数据类型，见书P35

array([1., 2., 6., 3.], dtype=float32)

## np.zeros
>指定长度，元素都是0的数组

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## np.ones
>创建3*5的浮点型数组，其数值都是1

In [7]:
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full
>创建3*3的浮点型数组，并指定全部元素的数值

In [8]:
np.full((3, 5), True)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## np.arange(m, n, s)
>区间$[m, n)$， 步长为s

In [9]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

## np.linspace(m, n, s)
>区间$[m, n]$平均取s个数

In [10]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

## np.eye
>np.eye(m)单位矩阵(方阵)数组

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## np.empty
>np.empty(m) 空数组，数组的值是内存空间中的任意值

In [12]:
np.empty(3)

array([3., 2., 1.])

## 随机数数组

In [13]:
# 0～1均匀分布的数组
np.random.random((3, 3))

array([[0.26936195, 0.39879645, 0.79225697],
       [0.35143152, 0.25780564, 0.24246059],
       [0.29438609, 0.2747474 , 0.13923597]])

In [14]:
# 正态分布的随机数组
## 均值：0，标准差：1
np.random.normal(0, 1, (3, 5))

array([[ 0.89390747, -0.52100929,  0.51164045,  1.28300781, -0.2419535 ],
       [ 0.65482642,  0.43673988, -1.94596724, -0.08134469, -0.57776049],
       [-1.70245112, -1.31499068,  2.11253724,  2.71203685, -1.82487455]])

In [15]:
# 区间内的随机整数数组
## 区间[0, 10)
np.random.randint(0, 10, (3, 5))

array([[0, 5, 9, 5, 9],
       [6, 9, 7, 1, 0],
       [5, 4, 5, 0, 1]])

***

# 查看数组的属性

_2021.03.21_

## 维度、shape、size

In [16]:
# 创建三个数组

np.random.seed(0) # ^ 设置随机数种子，使每次执行程序都能生成相同的数值

x1 = np.random.randint(10, size=6) # * 创建一个[0,10)内取值，数组有6个元素
x2 = np.random.randint(10, size=(3, 4)) # * 创建一个[0,10)内取值，数组有3个元素，每个元素中还有4个元素
x3 = np.random.randint(10, size=(3, 4, 5)) # * 创建一个[0,10)内取值，数组有3个元素，每个元素又是（4， 5）的
print("x1:\n", x1)
print("x2:\n", x2)
print("x3:\n", x3)

x1:
 [5 0 3 3 7 9]
x2:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3:
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [18]:
# 查看每个数组的维度
print("x1 ndim: ", x1.ndim)
print("x2 ndim: ", x2.ndim)
print("x3 ndim: ", x3.ndim)

x1 ndim:  1
x2 ndim:  2
x3 ndim:  3


In [19]:
'''
# * 查看每个数组的shape
'''
print("x1 shape: ", x1.shape)
print("x2 shape: ", x2.shape)
print("x3 shape: ", x3.shape)

x1 shape:  (6,)
x2 shape:  (3, 4)
x3 shape:  (3, 4, 5)


In [20]:
'''
# * 查看数组中元素的总个数
'''
print("x1 size: ", x1.size)
print("x2 size: ", x2.size)
print("x3 size: ", x3.size)

x1 size:  6
x2 size:  12
x3 size:  60


## 数组元素的数据类型

In [21]:
x4 = np.full((2, 3), True)
x5 = np.zeros(3)
print("x4:\n", x4)
print("x5:\n", x5)
print("x4 dtype: ", x4.dtype)
print("x5 dtype: ", x5.dtype)

x4:
 [[ True  True  True]
 [ True  True  True]]
x5:
 [0. 0. 0.]
x4 dtype:  bool
x5 dtype:  float64


## 元素字节、数组总字节

In [22]:
print("itemsize: ", x4.itemsize, "bytes")
print("nbytes:", x4.nbytes, "bytes")

itemsize:  1 bytes
nbytes: 6 bytes


# 数组索引
>获取数组中的单个元素

In [23]:
# 一维数组的索引
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[0]

5

In [25]:
x1[-1]

9

In [26]:
# 二维数组的索引
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0, 1]

5

In [28]:
x2[0][1] # 与上面的索引方式等价

5

# 数组切片
>x[start:stop:step]
>切片返回的是数组的视图，因此对切片的赋值会修改原数组

## 一维数组的切片  
step为正数的情况：  
若参数未指定，则默认值为star=0, stop=size, step=1

In [30]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x1[:5] # * x1的前5个元素

array([0, 1, 2, 3, 4])

In [32]:
x1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
x1[::2] # 每隔一个元素 

array([0, 2, 4, 6, 8])

In [34]:
# step为负数的情况：
# start为索引的开始，默认为size
# stop为索引的终止，应比start小，默认为0

In [35]:
x1[9:7:-1]

array([9, 8])

In [36]:
x1[:8:-1]

array([9])

In [37]:
x1[5::-2]

array([5, 3, 1])

In [38]:
x1[3:7:-1]

array([], dtype=int64)

## 多维数组的切片

In [39]:
x2 # 数组中有3个元素，每个元素中又有4个

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
x2[:2, 1:3] # 不同维度，逗号分隔

array([[5, 2],
       [6, 8]])

In [41]:
x2[::-1] # 只逆序第一维元素

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [42]:
x2[::-1, ::-1] # 两个维度都逆序

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

## 获取数组的行或列

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2[0] # 获取第1行

array([3, 5, 2, 4])

In [45]:
x2[:, 1] # 获取第2列

array([5, 6, 6])

In [46]:
x2[:, 1:2] # 注意与上面的区别

array([[5],
       [6],
       [6]])

## 切片副本
>切片返回的是数组的视图，因此对切片的赋值会修改原数组<br>
>可以通过copy()的方法来创建副本，避免修改原数组

In [47]:
# 展示切片会修改原数组
x2 = np.random.randint(10, size=(3, 4))
print("x2:\n", x2)
x2_sub = x2[:2, 2:4]
print("x2_sub:\n ", x2_sub)
x2_sub[0][1] = 99
print("操作后的x2_sub:\n ", x2_sub)
print("操作后的x2:\n", x2)

x2:
 [[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]
x2_sub:
  [[4 4]
 [3 7]]
操作后的x2_sub:
  [[ 4 99]
 [ 3  7]]
操作后的x2:
 [[ 4  3  4 99]
 [ 8  4  3  7]
 [ 5  5  0  1]]


In [48]:
# copy操作
x2 = np.random.randint(10, size=(3, 4))
print("x2:\n", x2)
x2_sub_copy = x2[:2, 2:4].copy()
print("x2_sub_copy:\n ", x2_sub_copy)
x2_sub_copy[0][1] = 99
print("操作后的x2_sub_copy:\n ", x2_sub_copy)
print("操作后的x2:\n", x2)

x2:
 [[5 9 3 0]
 [5 0 1 2]
 [4 2 0 3]]
x2_sub_copy:
  [[3 0]
 [1 2]]
操作后的x2_sub_copy:
  [[ 3 99]
 [ 1  2]]
操作后的x2:
 [[5 9 3 0]
 [5 0 1 2]
 [4 2 0 3]]


# 数组变形

## reshape()函数
>reshape()里面是以元组的形式表示的维度

In [50]:
# 将一维数组中的9个元素放进（3，3）的矩阵中
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# 将一维数组转换成行向量或列向量
x = np.array([0, 1, 2, 3, 4, 5])
print(x)
x_row = x.reshape((1, x.size))
print("x_row: ", x_row)
x_column = x.reshape((x.size, 1))
print("x_column: \n", x_column)

[0 1 2 3 4 5]
x_row:  [[0 1 2 3 4 5]]
x_column: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


## newaxis关键字

In [64]:
# 将一维数组转换成行向量或列向量
x = np.array([0, 1, 2, 3, 4, 5])
print(x)
x_row = x[np.newaxis, :]
x_column = x[:, np.newaxis]
print("x_row: ", x_row)
print("x_column: \n", x_column)

[0 1 2 3 4 5]
x_row:  [[0 1 2 3 4 5]]
x_column: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


# 数组的拼接

## np.concatenate
> np.concatenate([待拼接数组的列表])

In [69]:
x = np.array([1, 1, 1])
y = np.array([2, 3, 4, 5])
z = np.array([99, 99])
x_puls_y = np.concatenate([x, y, z])
x_puls_y

array([ 1,  1,  1,  2,  3,  4,  5, 99, 99])